trigger:
- master

pool:
  vmImage: 'ubuntu-latest' 

steps:
 - task: Docker@2
   displayName: Build an image
   inputs:
     containerRegistry: 'DockerHubKoen'
     repository: 'pipelines-javascript-docker'
     command: 'buildAndPush'
     Dockerfile: '**/Dockerfile'
     tags: |
       $(Build.BuildId)
       latest


