trigger:
- master

pool:
  vmImage: 'ubuntu-latest' 

variables:
    imageName: 'pipelines-javascript-docker'

steps:
 - task: Docker@2
   displayName: Build an image
   inputs:
     containerRegistry: 'DockerHubKoen'
     repository: $(imageName)
     command: 'buildAndPush'
     Dockerfile: app/Dockerfile
